services:
  - type: web
    name: monchat-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python nltk_setup.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0 # Most stable version for TensorFlow 2.x
